### ISSUE TITLE
Excellent Work! I have some questions to ask.

### ISSUE THREAD

**Issue by Lixuanhe** [snldmt/BAGS#2]
In the following code, which folders correspond to DATAPATH and deblurdata respectively?
OMP_NUM_THREADS=4 CUDA_VISIBLE_DEVICES=${gpu} python train.py \
    -s DATAPATH/${scene} \
    -m deblurdata/${scene} \
    --init_dgt 0.0006 --iterations 46000 --ms_steps 6000 --min_opacity 0.1 \
    --eval -r 4 --port $(expr 6009 + $gpu) --kernel_size 0.1 \
    --llffhold ${llffhold}

**Comment by snldmt** [comment]
`-s` specifies the input path while `-m` specifies the output path. You can change them to your data path and desired output path.
