### ISSUE TITLE
Mix resolution dataset on Mip Nerf 360 dataset

### ISSUE THREAD

**Issue by phongnhhn92** [snldmt/BAGS#3]
Hi,

I have a question about your mix resolution dataset as described in the paper. From my understanding, you guys downscale the image to 4X and then up-scale it again to the original resolution. After than, you use colmap or Nerfstudio to get the camera pose. Would you mind sharing that dataset since the link in the readme is from the original Mip-nerf 360.

**Comment by snldmt** [comment]
Hi thanks for your interest in our work. Sure, you can download the images and sfm from [here](https://livejohnshopkins-my.sharepoint.com/:u:/g/personal/ytang67_jh_edu/ETHb6cWcpu9KpYt_Tz88YrYBcCTm1ieTdTf5y6LFgxAVwQ?e=K8Q2b6).
